apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-engineer-production
  namespace: production
subjects:
  - kind: ServiceAccount
    name: platform-engineer
    namespace: default
roleRef:
  kind: ClusterRole
  name: platform-engineer
  apiGroup: rbac.authorization.k8s.io
