apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-fail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness-fail
  template:
    metadata:
      labels:
        app: readiness-fail
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        readinessProbe:
          httpGet:
            path: /nonexistent
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  selector:
    app: readiness-fail
  ports:
  - port: 80
